play_motion:
  controllers: [arm_controller, head_controller, torso_controller]

  motions:
    fast_home:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.25, 0.20, 0.35, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 0.5
      - positions: [0.18, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 2.0
      - positions: [0.15, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 3.5
      meta:
        name: fast_home
        usage: tiago_sim_hospital
        description: 'Go home, but fast'

    look_down:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, -0.5]
        time_from_start: 1.0
      meta:
        name: look_down
        usage: tiago_sim_hospital
        description: 'Bow your head forward.'