play_motion:
  controllers: [arm_controller, head_controller, torso_controller]

  motions:
    fast_home:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.25, 0.20, 0.35, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 0.5
      - positions: [0.18, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 2.0
      - positions: [0.15, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 3.5
      meta:
        name: fast_home
        usage: tiago_sim_hospital
        description: 'Go home, but fast'

    look_down:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, -0.5]
        time_from_start: 1.0
      meta:
        name: look_down
        usage: tiago_sim_hospital
        description: 'Bow your head forward.'

    look_forward:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, 0]
        time_from_start: 1.0
      meta:
        name: look_forward
        usage: tiago_sim_hospital
        description: 'Look forward.'

    center_arm:
      joints: [arm_1_joint]
      points:
      - positions: [1.57]
        time_from_start: 1.0
      meta:
        name: center_arm
        usage: tiago_sim_hospital
        description: 'Move first arm joint to the center of the robot (1.57).'

    level_arm:
      joints: [arm_2_joint]
      points:
      - positions: [0]
        time_from_start: 1.0
      meta:
        name: level_arm
        usage: tiago_sim_hospital
        description: 'Move second arm joint to horizontal position (0).'

    arm_left:
      joints: [arm_1_joint]
      points:
      - positions: [0.07]
        time_from_start: 1.0
      meta:
        name: arm_left
        usage: tiago_sim_hospital
        description: 'Move first arm joint maximum to the left (0.07).'